//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoApp.CryptoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CryptoServiceReference.ICryptoService")]
    public interface ICryptoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/Crypt", ReplyAction="http://tempuri.org/ICryptoService/CryptResponse")]
        byte[] Crypt(byte[] input, CryptoLib.Algorithm a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/Crypt", ReplyAction="http://tempuri.org/ICryptoService/CryptResponse")]
        System.Threading.Tasks.Task<byte[]> CryptAsync(byte[] input, CryptoLib.Algorithm a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/DeCrypt", ReplyAction="http://tempuri.org/ICryptoService/DeCryptResponse")]
        byte[] DeCrypt(byte[] input, CryptoLib.Algorithm a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/DeCrypt", ReplyAction="http://tempuri.org/ICryptoService/DeCryptResponse")]
        System.Threading.Tasks.Task<byte[]> DeCryptAsync(byte[] input, CryptoLib.Algorithm a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICryptoServiceChannel : CryptoApp.CryptoServiceReference.ICryptoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CryptoServiceClient : System.ServiceModel.ClientBase<CryptoApp.CryptoServiceReference.ICryptoService>, CryptoApp.CryptoServiceReference.ICryptoService {
        
        public CryptoServiceClient() {
        }
        
        public CryptoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CryptoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] Crypt(byte[] input, CryptoLib.Algorithm a) {
            return base.Channel.Crypt(input, a);
        }
        
        public System.Threading.Tasks.Task<byte[]> CryptAsync(byte[] input, CryptoLib.Algorithm a) {
            return base.Channel.CryptAsync(input, a);
        }
        
        public byte[] DeCrypt(byte[] input, CryptoLib.Algorithm a) {
            return base.Channel.DeCrypt(input, a);
        }
        
        public System.Threading.Tasks.Task<byte[]> DeCryptAsync(byte[] input, CryptoLib.Algorithm a) {
            return base.Channel.DeCryptAsync(input, a);
        }
    }
}
